### ISSUE TITLE
/usr/bin/xcrun simctl terminateApp  ... exited with code 4

### ISSUE THREAD

**Issue by stoefln** [appium/node-simctl#138]
I try to run following code in my electron application:

```
self.simctl = new Simctl()
self.simctl.udid = "8EC67616-5D0F-4694-AF27-A2D01DCD1A30"
await self.simctl.launchApp('com.mycomp.myapp')
```

But I get following error:
`/usr/bin/xcrun simctl launch 8EC67616-5D0F-4694-AF27-A2D01DCD1A30 com.mycomp.myapp' exited with code 4`

this command works without problem in the terminal though:
`/usr/bin/xcrun simctl launch 8EC67616-5D0F-4694-AF27-A2D01DCD1A30 com.mycomp.myapp`

**Comment by mykola-mokhnach** [comment]
have you checked the actual returned code in the terminal? It could be that visually everything is ok, although the returned exit code is still not equal to zero

**Comment by stoefln** [comment]
Nevermind. It is a string encoding issue. My application passes the string with the wrong encoding.
