### ISSUE TITLE
Implement clipboard control

### ISSUE THREAD

**Issue by crisp2u** [appium/node-simctl#39]
Hi guys,

Shouldn't be possible to implement clipboard commands also ? 'I'm trying to find a way to access simulator clipboard from appium.

Thanks!

**Comment by imurchie** [comment]
Yes. Should be possible. A quick try from the command line didn't yield anything working, though.

**Comment by crisp2u** [comment]
`xcrun simctl` shows this commands available:

```
	pbsync              Sync the pasteboard content from one pasteboard to another.
	pbcopy              Copy standard input onto the device pasteboard.
	pbpaste             Print the contents of the device's pasteboard to standard output.
```

I've tested this ans seems to work:
`echo "Test" | xcrun simctl pbcopy booted && xcrun simctl pbpaste booted`

**Comment by imurchie** [comment]
Yeah. Didn't work on one sim, works on another. Probably my error :)

**Comment by imurchie** [comment]
I've added an enhancement ticket to our backlog: https://github.com/appium/appium/issues/8760

**Comment by crisp2u** [comment]
Thanks, for me it's a long shot, I need this implemented all the way back to appium :-)

**Comment by mykola-mokhnach** [comment]
@crisp2u The necessary changes have been merged into Appium beta. Please check https://github.com/mykola-mokhnach/appium/blob/8f9645d21c3c31c4517255771baf835f2fbea3f1/docs/en/writing-running-appium/ios-xctest-pasteboard.md

**Comment by MiroslavPetrik** [comment]
@crisp2u Hi, in what version did the command
```
echo "Test" | xcrun simctl pbcopy booted && xcrun simctl pbpaste booted
```
work for you?

I have:
```
$ xcrun --version                                                          
// xcrun version 43.

$xcrun simctl --version
// @(#)PROGRAM:simctl  PROJECT:CoreSimulator-581.2
```

And it prints nothing for me.

**Comment by crisp2u** [comment]
@MiroslavPetrik I'm sorry, I'm not involved at the moment in any work with iOS and Appium tasks. Did you check if the emulator is running and what emulator is running ? As far as I remember "booted" is just an alias to whatever is running at the moment but It think xcrun can also identify the emulator using the id

**Comment by MiroslavPetrik** [comment]
@crisp2u I had single simulator running. It worked few times, after I manually checked/unchecked the `Automatically Sync Pasteboard` option in the simulator Edit menu, so the `booted` alias worked.
But the behaviour was unstable, I couldn't get it working consistently returning value each time I ran the command.
