### ISSUE TITLE
getPasteboard returns empty value

### ISSUE THREAD

**Issue by MiroslavPetrik** [appium/node-simctl#79]
I tried the API, and noticed that the `getPasteboard` somehow doesn't work.

Then I looked into the tests and found a comment
https://github.com/appium/node-simctl/blob/762ce13a98e680a9e20f6ab45712b949496589ca/test/simctl-e2e-specs.js#L184

The tests actually runs multiple times, so it's kinda hacky.
I tried the same in my use case, got the value after >300th attempt which is unusable.

Is there a better solution for this?
In the test TODO xcode v9 is mentioned, I'm running v10.1, still this behaviour...

**Comment by KazuCocoa** [comment]
The code calls `xcrun simctl pbpaste`. so, it depends on macOS and Xcode...

(We has https://github.com/appium/WebDriverAgent . If you use Appium, you can call http://appium.io/docs/en/commands/device/clipboard/get-clipboard/ instead of this)
